services:
  postgres:
    image: postgres:16-alpine
    container_name: commertize_postgres
    environment:
      POSTGRES_USER: commertize
      POSTGRES_PASSWORD: commertize
      POSTGRES_DB: commertize_dev
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U commertize"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
    driver: local
